--!strict
--!native
--!optimize 2
--!nolint LocalShadow
--#selene: allow(shadowing)
-- File generated by Blink v0.18.6 (https://github.com/1Axen/Blink)
-- This file is not meant to be edited

_G._BLINK = _G._BLINK or {}
if _G._BLINK["BLINK"] then
	error("[Blink]: An instance of blink is already running with the remote scope \"BLINK\". Change the remote scope of either instance to avoid conflicts.")
end
_G._BLINK["BLINK"] = true
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local BASE_EVENT_NAME = "BLINK"
local Invocations = 0

local SendSize = 64
local SendOffset = 0
local SendCursor = 0
local SendBuffer = buffer.create(64)
local SendInstances = {}

local RecieveCursor = 0
local RecieveBuffer = buffer.create(64)

local RecieveInstances = {}
local RecieveInstanceCursor = 0

local Null = newproxy()

type Entry = {
    value: any,
    next: Entry?
}

type Queue = {
    head: Entry?,
    tail: Entry?
}

type BufferSave = {
    Size: number, 
    Cursor: number, 
    Buffer: buffer, 
    Instances: {Instance}
}

local function Read(Bytes: number)
    local Offset = RecieveCursor
    RecieveCursor += Bytes
    return Offset
end

local function Save(): BufferSave
    return {
        Size = SendSize,
        Cursor = SendCursor,
        Buffer = SendBuffer,
        Instances = SendInstances
    }
end

local function Load(Save: BufferSave?)
    if Save then
        SendSize = Save.Size
        SendCursor = Save.Cursor
        SendOffset = Save.Cursor
        SendBuffer = Save.Buffer
        SendInstances = Save.Instances
        return
    end

    SendSize = 64
    SendCursor = 0
    SendOffset = 0
    SendBuffer = buffer.create(64)
    SendInstances = {}
end

local function Invoke()
    if Invocations == 255 then
        Invocations = 0
    end

    local Invocation = Invocations
    Invocations += 1
    return Invocation
end

local function Allocate(Bytes: number)
    local InUse = (SendCursor + Bytes)
    if InUse > SendSize then
        --> Avoid resizing the buffer for every write
        while InUse > SendSize do
            SendSize *= 1.5
        end

        local Buffer = buffer.create(SendSize)
        buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
        SendBuffer = Buffer
    end

    SendOffset = SendCursor
    SendCursor += Bytes
    
    return SendOffset
end

local function CreateQueue(): Queue
    return {
        head = nil,
        tail = nil
    }
end

local function Pop(queue: Queue): any
    local head = queue.head
    if head == nil then
        return
    end

    queue.head = head.next
    return head.value
end

local function Push(queue: Queue, value: any)
    local entry: Entry = {
        value = value,
        next = nil
    }

    if queue.tail ~= nil then
        queue.tail.next = entry
    end

    queue.tail = entry

    if queue.head == nil then
        queue.head = entry
    end
end

local Calls = table.create(256)

local Events: any = {
    Reliable = table.create(256),
    Unreliable = table.create(256)
}

local Queue: any = {
    Reliable = table.create(256),
    Unreliable = table.create(256)
}

local SerdesEvent = "?"
local SerdesThread: thread?
Events.Reliable[0] = {}
Queue.Reliable[0] = table.create(256)
export type Action = ("Play" | "Stop")
export type AnimationIntent = { CharacterId: string, AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }
export type RelayedIntent = { AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }
export type ActiveGroupAnims = {[string]: string}
export type SnapshotData = { StateName: string, ActiveGroupAnims: {[string]: string}, SequenceNumber: number, ServerTime: number }
local function ReadEVENT_SendIntent(): ({ CharacterId: string, AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number })
	-- Read BLOCK: 13 bytes
	local BLOCK_START = Read(13)
	local Value = {} :: any
	local Length = buffer.readu16(RecieveBuffer, BLOCK_START + 0)
	Value.CharacterId = buffer.readstring(RecieveBuffer, Read(Length), Length)
	Length = buffer.readu16(RecieveBuffer, BLOCK_START + 2)
	Value.AnimationName = buffer.readstring(RecieveBuffer, Read(Length), Length)
	Value.Action = true :: any
	local Index = buffer.readu8(RecieveBuffer, BLOCK_START + 4)
	if Index == 0 then
		Value.Action = "Play"
	elseif Index == 1 then
		Value.Action = "Stop"
	else
		error(`Unexpected enum: {Index}`)
	end
	Value.Timestamp = buffer.readf64(RecieveBuffer, BLOCK_START + 5)
	return Value
end

local function WriteEVENT_RelayIntent(Value: { AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }): ()
	-- Allocate BLOCK: 12 bytes
	local BLOCK_START = Allocate(12)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 1)
	local Length = #Value.AnimationName
	buffer.writeu16(SendBuffer, BLOCK_START + 1, Length)
	Allocate(Length)
	buffer.writestring(SendBuffer, SendOffset, Value.AnimationName, Length)
	if Value.Action == "Play" then
		buffer.writeu8(SendBuffer, BLOCK_START + 3, 0)
	elseif Value.Action == "Stop" then
		buffer.writeu8(SendBuffer, BLOCK_START + 3, 1)
	else
		error(`Unexpected enum: {Value.Action}, expected one of "Play" or "Stop".`)
	end
	buffer.writef64(SendBuffer, BLOCK_START + 4, Value.Timestamp)
end

local function WriteEVENT_SendSnapshot(Value: { StateName: string, ActiveGroupAnims: {[string]: string}, SequenceNumber: number, ServerTime: number }): ()
	-- Allocate BLOCK: 15 bytes
	local BLOCK_START = Allocate(15)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 2)
	local Length = #Value.StateName
	buffer.writeu16(SendBuffer, BLOCK_START + 1, Length)
	Allocate(Length)
	buffer.writestring(SendBuffer, SendOffset, Value.StateName, Length)
	local Elements_1 = 0
	for Key_1, Element_1 in Value.ActiveGroupAnims do
		Elements_1 += 1
		local Length = #Key_1
		local OFFSET_0 = Allocate(2)
		buffer.writeu16(SendBuffer, OFFSET_0, Length)
		Allocate(Length)
		buffer.writestring(SendBuffer, SendOffset, Key_1, Length)
		local Length = #Element_1
		local OFFSET_1 = Allocate(2)
		buffer.writeu16(SendBuffer, OFFSET_1, Length)
		Allocate(Length)
		buffer.writestring(SendBuffer, SendOffset, Element_1, Length)
	end
	buffer.writeu16(SendBuffer, BLOCK_START + 3, Elements_1)
	buffer.writeu16(SendBuffer, BLOCK_START + 5, Value.SequenceNumber)
	buffer.writef64(SendBuffer, BLOCK_START + 7, Value.ServerTime)
end

if not RunService:IsRunning() then
	local NOOP = function() end
	local Returns = table.freeze({
	SendIntent = {
		On = NOOP
	},
	RelayIntent = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	SendSnapshot = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	})
	return Returns :: BLINK_EVENTS_SYMBOL
end

if not RunService:IsServer() then
    error("Server network module can only be required from the server.")
end

local Reliable: RemoteEvent = ReplicatedStorage:FindFirstChild(BASE_EVENT_NAME .. "_RELIABLE_REMOTE") :: RemoteEvent
if not Reliable then
    local RemoteEvent = Instance.new("RemoteEvent")
    RemoteEvent.Name = BASE_EVENT_NAME .. "_RELIABLE_REMOTE"
    RemoteEvent.Parent = ReplicatedStorage
    Reliable = RemoteEvent
end

local Unreliable: UnreliableRemoteEvent = ReplicatedStorage:FindFirstChild(BASE_EVENT_NAME .. "_UNRELIABLE_REMOTE") :: UnreliableRemoteEvent
if not Unreliable then
    local UnreliableRemoteEvent = Instance.new("UnreliableRemoteEvent")
    UnreliableRemoteEvent.Name = BASE_EVENT_NAME .. "_UNRELIABLE_REMOTE"
    UnreliableRemoteEvent.Parent = ReplicatedStorage
    Unreliable = UnreliableRemoteEvent
end

local PlayersMap: {[Player]: BufferSave} = {}

Players.PlayerRemoving:Connect(function(Player)
    PlayersMap[Player] = nil
end)

local function StepReplication()
    for Player, Send in PlayersMap do
        if Send.Cursor <= 0 then
            continue
        end

        local Buffer = buffer.create(Send.Cursor)
        buffer.copy(Buffer, 0, Send.Buffer, 0, Send.Cursor)
        Reliable:FireClient(Player, Buffer, Send.Instances)

        Send.Size = 64
        Send.Cursor = 0
        Send.Buffer = buffer.create(64)
        table.clear(Send.Instances)
    end
end
RunService.Heartbeat:Connect(StepReplication)
Reliable.OnServerEvent:Connect(function(Player: Player, Buffer: buffer, Instances: {Instance})
	RecieveCursor = 0
	RecieveBuffer = Buffer
	RecieveInstances = Instances
	RecieveInstanceCursor = 0
	local Size = buffer.len(RecieveBuffer)
	if SerdesThread and coroutine.status(SerdesThread) == "suspended" then
		warn(`[Blink]: Yielded in a Sync call. Event "{SerdesEvent}" uses a Sync call, consider using an Async call instead.`)
		coroutine.close(SerdesThread)
	end
	SerdesThread = coroutine.running()
	while (RecieveCursor < Size) do
		-- Read BLOCK: 1 bytes
		local BLOCK_START = Read(1)
		local Index = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
		if Index == 0 then
			local Value: { CharacterId: string, AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number } = ReadEVENT_SendIntent()
			if #Events.Reliable[0] > 0 then
				for _, Listener in Events.Reliable[0] do
					task.spawn(Listener, Player, Value)
				end
			else
				if #Queue.Reliable[0] > 256 then
					warn("[Blink]: Event queue of \"SendIntent\" exceeded 256, did you forget to implement a listener?")
				end
				table.insert(Queue.Reliable[0], {Player, Value} :: {any})
			end
		end
	end
end)
Unreliable.OnServerEvent:Connect(function(Player: Player, Buffer: buffer, Instances: {Instance})
	RecieveCursor = 0
	RecieveBuffer = Buffer
	RecieveInstances = Instances
	RecieveInstanceCursor = 0
	local Size = buffer.len(RecieveBuffer)
	if SerdesThread and coroutine.status(SerdesThread) == "suspended" then
		warn(`[Blink]: Yielded in a Sync call. Event "{SerdesEvent}" uses a Sync call, consider using an Async call instead.`)
		coroutine.close(SerdesThread)
	end
	SerdesThread = coroutine.running()
	while (RecieveCursor < Size) do
		-- Read BLOCK: 1 bytes
		local BLOCK_START = Read(1)
		local Index = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
	end
end)


local Returns = table.freeze({
	StepReplication = StepReplication,

	SendIntent = {
		On = function(Listener: (Player: Player, Value: { CharacterId: string, AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }) -> ()): () -> ()
			table.insert(Events.Reliable[0], Listener)
			for Index, Arguments in Queue.Reliable[0] do
				task.spawn(Listener, table.unpack(Arguments))
			end
			Queue.Reliable[0] = {}
			return function (): ()
				local Index = table.find(Events.Reliable[0], Listener)
				if Index ~= nil then
					table.remove(Events.Reliable[0], Index)
				end
			end
		end
	},
	RelayIntent = {
		Fire = function(Player: Player, Value: { AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }): ()
			Load(PlayersMap[Player])
			WriteEVENT_RelayIntent(Value)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value: { AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }): ()
			Load()
			WriteEVENT_RelayIntent(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value: { AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }): ()
			Load()
			WriteEVENT_RelayIntent(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value: { AnimationName: string, Action: ("Play" | "Stop"), Timestamp: number }): ()
			Load()
			WriteEVENT_RelayIntent(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
	SendSnapshot = {
		Fire = function(Player: Player, Value: { StateName: string, ActiveGroupAnims: {[string]: string}, SequenceNumber: number, ServerTime: number }): ()
			Load(PlayersMap[Player])
			WriteEVENT_SendSnapshot(Value)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value: { StateName: string, ActiveGroupAnims: {[string]: string}, SequenceNumber: number, ServerTime: number }): ()
			Load()
			WriteEVENT_SendSnapshot(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value: { StateName: string, ActiveGroupAnims: {[string]: string}, SequenceNumber: number, ServerTime: number }): ()
			Load()
			WriteEVENT_SendSnapshot(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value: { StateName: string, ActiveGroupAnims: {[string]: string}, SequenceNumber: number, ServerTime: number }): ()
			Load()
			WriteEVENT_SendSnapshot(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
})
type BLINK_EVENTS_SYMBOL = typeof(Returns)
return Returns :: BLINK_EVENTS_SYMBOL